//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToMoToStudy
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiHoc()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.CHITIET_CT_HOC = new HashSet<CHITIET_CT_HOC>();
            this.FileGiangViens = new HashSet<FileGiangVien>();
            this.FileHocViens = new HashSet<FileHocVien>();
        }
    
        public int IdBaiHoc { get; set; }
        public string TenBaiHoc { get; set; }
        public string NoiDung { get; set; }
        public string Video { get; set; }
        public Nullable<bool> ChoPhepNopBai { get; set; }
        public int IdNguoiDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_CT_HOC> CHITIET_CT_HOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileGiangVien> FileGiangViens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileHocVien> FileHocViens { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
