//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToMoToStudy
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien_TracNghiem
    {
        public int IdNopBai { get; set; }
        public int IdSinhVien { get; set; }
        public int IdTracNghiem { get; set; }
        public Nullable<System.DateTime> NgayLam { get; set; }
        public Nullable<System.DateTime> NgayNop { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
    }
}
