//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToMoToStudy
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.FileHocViens = new HashSet<FileHocVien>();
            this.SinhVien_TracNghiem = new HashSet<SinhVien_TracNghiem>();
            this.SinhVien_TL_DapAn = new HashSet<SinhVien_TL_DapAn>();
            this.SVLops = new HashSet<SVLop>();
            this.SinhVien_BaiLam_TracNghiem = new HashSet<SinhVien_BaiLam_TracNghiem>();
        }
    
        public int IdSinhVien { get; set; }
        public string Mssv { get; set; }
        public string MaLopSv { get; set; }
        public int IdNguoiDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileHocVien> FileHocViens { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinhVien_TracNghiem> SinhVien_TracNghiem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinhVien_TL_DapAn> SinhVien_TL_DapAn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SVLop> SVLops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinhVien_BaiLam_TracNghiem> SinhVien_BaiLam_TracNghiem { get; set; }
    }
}
