//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToMoToStudy
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien_TL_DapAn
    {
        public int IdSinhVien { get; set; }
        public int IdCauHoiTuLuan { get; set; }
        public string DapAn { get; set; }
        public Nullable<decimal> DiemTuLuan { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
        public virtual TuLuan_CauHoi TuLuan_CauHoi { get; set; }
    }
}
