//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToMoToStudy
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien_BaiLam_TracNghiem
    {
        public int IdBaiLam { get; set; }
        public int IdDapAn { get; set; }
        public int IdCauHoi { get; set; }
        public int IdSinhVien { get; set; }
        public Nullable<System.DateTime> NgayNop { get; set; }
        public Nullable<int> IdTracNghiem { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
        public virtual TracNghiem TracNghiem { get; set; }
        public virtual TracNghiem_CauHoi TracNghiem_CauHoi { get; set; }
        public virtual TracNghiem_DapAn TracNghiem_DapAn { get; set; }
    }
}
