//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToMoToStudy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongBao()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.FileGiangViens = new HashSet<FileGiangVien>();
        }
    
        public int IdThaoLuan { get; set; }
        public string CauThaoLuan { get; set; }
        public int IdLopHoc { get; set; }
        public int IdNguoiDung { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileGiangVien> FileGiangViens { get; set; }
        public virtual LopHoc LopHoc { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
