//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToMoToStudy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TracNghiem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TracNghiem()
        {
            this.CHITIET_CT_HOC = new HashSet<CHITIET_CT_HOC>();
            this.SinhVien_BaiLam_TracNghiem = new HashSet<SinhVien_BaiLam_TracNghiem>();
            this.TracNghiem_CauHoi = new HashSet<TracNghiem_CauHoi>();
        }
    
        public int IdTracNghiem { get; set; }
        public string TenTracNghiem { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> ThoiGian { get; set; }
        public Nullable<System.DateTime> HanChot { get; set; }
        public int IdNguoiDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_CT_HOC> CHITIET_CT_HOC { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinhVien_BaiLam_TracNghiem> SinhVien_BaiLam_TracNghiem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TracNghiem_CauHoi> TracNghiem_CauHoi { get; set; }
    }
}
