//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToMoToStudy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuLuan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TuLuan()
        {
            this.CHITIET_CT_HOC = new HashSet<CHITIET_CT_HOC>();
            this.TuLuan_CauHoi = new HashSet<TuLuan_CauHoi>();
        }
    
        public int IdTuLuan { get; set; }
        public string TenTuLuan { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> ThoiGian { get; set; }
        public Nullable<System.DateTime> HanChot { get; set; }
        public int IdNguoiDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_CT_HOC> CHITIET_CT_HOC { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TuLuan_CauHoi> TuLuan_CauHoi { get; set; }
    }
}
